"""Changed purchase_product to association pattern

Revision ID: 4a3756fc9ac0
Revises: 69cfc61ecb5f
Create Date: 2022-11-12 23:50:57.579402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3756fc9ac0'
down_revision = '69cfc61ecb5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
