"""deleted columns

Revision ID: 4a4ac4eab226
Revises: c1dcfd75da9a
Create Date: 2022-11-12 02:15:15.967943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a4ac4eab226'
down_revision = 'c1dcfd75da9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appuser', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('appuser', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('appuser', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('appuser', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('appuser', 'updated')
    op.drop_column('appuser', 'created')
    op.add_column('product', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('product', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('product', 'updated')
    op.drop_column('product', 'created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('product', 'deleted_at')
    op.drop_column('product', 'deleted')
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    op.add_column('appuser', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('appuser', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('appuser', 'deleted_at')
    op.drop_column('appuser', 'deleted')
    op.drop_column('appuser', 'updated_at')
    op.drop_column('appuser', 'created_at')
    # ### end Alembic commands ###
