"""Added quantity to purchase_product table

Revision ID: 69cfc61ecb5f
Revises: 4dcef3c4afdf
Create Date: 2022-11-12 23:34:42.652274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cfc61ecb5f'
down_revision = '4dcef3c4afdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_product', 'purchase_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchase_product', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_product', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchase_product', 'purchase_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
