"""Added balance to appuser

Revision ID: 9c9500ce989c
Revises: 4a3756fc9ac0
Create Date: 2022-11-13 16:12:36.702769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9500ce989c'
down_revision = '4a3756fc9ac0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appuser', sa.Column('balance', sa.Numeric(), nullable=False, server_default="0"))
    op.alter_column('appuser', 'balance', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appuser', 'balance')
    # ### end Alembic commands ###
