"""Decimal precision in balance to 2 decimal places

Revision ID: b627c6cabe56
Revises: 9c9500ce989c
Create Date: 2022-11-13 17:19:44.687135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b627c6cabe56'
down_revision = '9c9500ce989c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
