"""initial

Revision ID: c1dcfd75da9a
Revises: 04b08960ceab
Create Date: 2022-11-11 21:49:04.880206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1dcfd75da9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appuser',
    sa.Column('appuser_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('passwd', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.CheckConstraint("length(phone) = 10 and phone ~ '^\\d+$'"),
    sa.PrimaryKeyConstraint('appuser_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('state',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('purchase',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('appuser_id', sa.Integer(), nullable=True),
    sa.Column('purchase_state', sa.Integer(), nullable=True),
    sa.Column('purchase_datetime', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['appuser_id'], ['appuser.appuser_id'], ),
    sa.ForeignKeyConstraint(['purchase_state'], ['state.state_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_table('shopping_cart',
    sa.Column('appuser_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appuser_id'], ['appuser.appuser_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('appuser_id', 'product_id')
    )
    op.create_table('finance_log',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('appuser_id', sa.Integer(), nullable=True),
    sa.Column('transaction_datetime', sa.DateTime(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('debet', sa.Numeric(), nullable=True),
    sa.Column('credit', sa.Numeric(), nullable=True),
    sa.Column('saldo', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['appuser_id'], ['appuser.appuser_id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.purchase_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('purchase_product',
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.purchase_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_product')
    op.drop_table('finance_log')
    op.drop_table('shopping_cart')
    op.drop_table('purchase')
    op.drop_table('state')
    op.drop_table('product')
    op.drop_table('appuser')
    # ### end Alembic commands ###
