"""Decimal precision in balance to 2 decimal places

Revision ID: ce85adfe1b54
Revises: b627c6cabe56
Create Date: 2022-11-13 17:21:57.960894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce85adfe1b54'
down_revision = 'b627c6cabe56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
